#!/bin/bash
PORT=3000 \
	DOMAIN="socialapp.teltecsolutions.com.br" \
	INSTAGRAM_CLIENT_ID="CHANGE_ME" \
	INSTAGRAM_CLIENT_SECRET="CHANGE_ME" \
	INSTAGRAM_ACCESS_TOKEN="CHANGE_ME" \
	TWITTER_CONSUMER_KEY="CHANGE_ME" \
	TWITTER_CONSUMER_SECRET="CHANGE_ME" \
	TWITTER_ACCESS_TOKEN_KEY="CHANGE_ME" \
	TWITTER_ACCESS_TOKEN_SECRET="CHANGE_ME" \
	node bin/www
